"""Sensor binary build service — generates embedded config and compiles."""
from __future__ import annotations

import asyncio
import json
import logging
import platform
import shutil
import tempfile
import time
import uuid
from dataclasses import dataclass
from pathlib import Path

log = logging.getLogger(__name__)

TARGET_MAP = {
    "linux-x86_64": {
        "triple": "x86_64-unknown-linux-musl",
        "default_buffer_mb": 100,
        "binary_name": "leetha-sensor",
    },
    "linux-arm": {
        "triple": "armv7-unknown-linux-musleabihf",
        "default_buffer_mb": 50,
        "binary_name": "leetha-sensor",
    },
    "linux-arm64": {
        "triple": "aarch64-unknown-linux-musl",
        "default_buffer_mb": 100,
        "binary_name": "leetha-sensor",
    },
    "linux-mips": {
        "triple": "mips-unknown-linux-musl",
        "default_buffer_mb": 10,
        "binary_name": "leetha-sensor",
    },
    "windows-x86_64": {
        "triple": "x86_64-pc-windows-gnu",
        "default_buffer_mb": 50,
        "binary_name": "leetha-sensor.exe",
    },
}

# Map current machine arch to detect native builds
_NATIVE_ARCH_MAP = {
    "x86_64": "x86_64",
    "aarch64": "aarch64",
    "armv7l": "armv7",
}


def _get_host_triple() -> str | None:
    """Detect the host Rust target triple."""
    import subprocess
    try:
        result = subprocess.run(
            ["rustc", "--version", "--verbose"],
            capture_output=True, text=True, timeout=5,
        )
        for line in result.stdout.splitlines():
            if line.startswith("host:"):
                return line.split(":", 1)[1].strip()
    except Exception:
        pass
    return None


def _is_native_target(target: str) -> bool:
    """Return True if the target matches the host architecture."""
    machine = platform.machine()
    native_prefix = _NATIVE_ARCH_MAP.get(machine)
    if not native_prefix:
        return False
    return TARGET_MAP[target]["triple"].startswith(native_prefix)


def _get_build_triple(target: str) -> str:
    """Get the Rust triple to use for building.

    For native builds, uses the host triple (which may be gnu instead of musl).
    For cross builds, uses the target triple from TARGET_MAP.
    """
    if _is_native_target(target):
        host = _get_host_triple()
        if host:
            return host
    return TARGET_MAP[target]["triple"]


def generate_embedded_rs(
    name: str,
    server: str,
    buffer_mb: int,
    ca_path: str,
    cert_path: str,
    key_path: str,
) -> str:
    """Generate the embedded.rs source file content."""
    safe_name = name.replace('"', '\\"')
    safe_server = server.replace('"', '\\"')
    return f'''// Auto-generated by leetha build server — do not edit manually.

pub const SENSOR_NAME: &str = "{safe_name}";
pub const SERVER_ADDR: &str = "{safe_server}";
pub const BUFFER_SIZE_MB: usize = {buffer_mb};
pub const CA_PEM: &[u8] = include_bytes!("{ca_path}");
pub const CERT_PEM: &[u8] = include_bytes!("{cert_path}");
pub const KEY_PEM: &[u8] = include_bytes!("{key_path}");
'''


def check_prerequisites(target: str) -> tuple[bool, str]:
    """Check if build tools are available. Returns (ok, message)."""
    if not shutil.which("rustc"):
        return False, "Rust toolchain not found. Install via: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"

    if not shutil.which("cargo"):
        return False, "cargo not found. Install Rust via: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"

    if not _is_native_target(target):
        if not shutil.which("cross"):
            return False, (
                "cross not installed (needed for cross-compilation). "
                "Run: cargo install cross"
            )
        if not shutil.which("docker"):
            return False, (
                "Docker not found (required by cross for cross-compilation). "
                "Install Docker: https://docs.docker.com/engine/install/"
            )
    return True, "ok"


@dataclass
class BuildRequest:
    name: str
    server: str
    target: str
    buffer_size_mb: int

    def __post_init__(self):
        if self.target not in TARGET_MAP:
            raise ValueError(
                f"Unknown target '{self.target}'. "
                f"Valid targets: {', '.join(TARGET_MAP.keys())}"
            )


class BuildHistory:
    """Persistent build history stored as JSON alongside the CA."""

    def __init__(self, data_dir: Path):
        self.path = data_dir / "sensor-builds.json"

    def _load(self) -> list[dict]:
        if self.path.exists():
            try:
                return json.loads(self.path.read_text())
            except Exception:
                return []
        return []

    def _save(self, entries: list[dict]) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(json.dumps(entries, indent=2))

    def record(self, request: BuildRequest, success: bool, download_id: str | None = None) -> dict:
        entries = self._load()
        entry = {
            "id": uuid.uuid4().hex[:12],
            "name": request.name,
            "server": request.server,
            "target": request.target,
            "buffer_size_mb": request.buffer_size_mb,
            "built_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "success": success,
            "download_id": download_id,
        }
        entries.insert(0, entry)
        # Keep last 50 builds
        entries = entries[:50]
        self._save(entries)
        return entry

    def list_builds(self) -> list[dict]:
        return self._load()

    def get_build(self, build_id: str) -> dict | None:
        for entry in self._load():
            if entry["id"] == build_id:
                return entry
        return None

    def delete_build(self, build_id: str) -> bool:
        entries = self._load()
        filtered = [e for e in entries if e["id"] != build_id]
        if len(filtered) == len(entries):
            return False
        self._save(filtered)
        return True


# Store for completed builds awaiting download
_build_artifacts: dict[str, dict] = {}
# Lock to prevent concurrent builds per target
_build_locks: dict[str, asyncio.Lock] = {}


def get_artifact(download_id: str) -> dict | None:
    """Retrieve a build artifact by download ID."""
    artifact = _build_artifacts.get(download_id)
    if artifact and time.time() - artifact["created"] > 600:
        _cleanup_artifact(download_id)
        return None
    return artifact


def _cleanup_artifact(download_id: str) -> None:
    """Remove a build artifact."""
    artifact = _build_artifacts.pop(download_id, None)
    if artifact and Path(artifact["path"]).exists():
        Path(artifact["path"]).unlink(missing_ok=True)


def _get_build_lock(target: str) -> asyncio.Lock:
    """Get or create a per-target build lock."""
    if target not in _build_locks:
        _build_locks[target] = asyncio.Lock()
    return _build_locks[target]


class SensorBuilder:
    """Builds a sensor binary with embedded config and certs."""

    def __init__(self, sensor_dir: Path, ca_dir: Path, data_dir: Path | None = None):
        self.sensor_dir = sensor_dir
        self.ca_dir = ca_dir
        self.history = BuildHistory(data_dir) if data_dir else None

    async def build(self, request: BuildRequest, progress_callback=None):
        """Build a sensor binary. Returns download_id on success, None on failure.

        Args:
            request: Build parameters.
            progress_callback: Async callable(stage: str, message: str).
                Stages: "certs", "config", "compile", "done", "error".
        """
        async def emit(stage: str, message: str):
            if progress_callback:
                await progress_callback(stage, message)

        target_info = TARGET_MAP[request.target]
        triple = _get_build_triple(request.target)
        binary_name = target_info["binary_name"]
        build_dir = self.sensor_dir / "build"

        lock = _get_build_lock(request.target)
        if lock.locked():
            await emit("error", f"A build for {request.target} is already in progress")
            return None

        async with lock:
            try:
                # Step 1: Generate certs
                await emit("certs", f"Generating certificates for {request.name}...")
                from leetha.capture.remote.ca import (
                    issue_cert, revoke_cert, list_certs,
                )

                build_dir.mkdir(parents=True, exist_ok=True)

                # Reuse existing cert if available, otherwise issue new one
                existing_cert = build_dir / f"{request.name}.crt"
                existing_key = build_dir / f"{request.name}.key"
                has_existing = existing_cert.exists() and existing_key.exists()

                if not has_existing:
                    # Check if cert was issued before but files aren't in build dir
                    try:
                        certs = list_certs(self.ca_dir)
                        has_active = any(
                            c["name"] == request.name and not c["revoked"]
                            for c in certs
                        )
                    except Exception:
                        has_active = False

                    if has_active:
                        # Cert exists in registry but not in build dir — re-issue
                        # (revoke old, issue new so files are in build_dir)
                        revoke_cert(self.ca_dir, request.name)

                    cert_path, key_path = issue_cert(self.ca_dir, request.name, build_dir)
                    await emit("certs", f"Issued certificate for {request.name}")
                else:
                    cert_path = existing_cert
                    key_path = existing_key
                    await emit("certs", f"Reusing existing certificate for {request.name}")

                ca_cert_path = build_dir / "ca.crt"
                shutil.copy2(self.ca_dir / "ca.crt", ca_cert_path)
                await emit("certs", "Certificates ready")

                # Step 2: Generate embedded.rs
                await emit("config", "Embedding configuration...")
                embedded_rs = generate_embedded_rs(
                    name=request.name,
                    server=request.server,
                    buffer_mb=request.buffer_size_mb,
                    ca_path="../build/ca.crt",
                    cert_path=f"../build/{request.name}.crt",
                    key_path=f"../build/{request.name}.key",
                )
                (self.sensor_dir / "src" / "embedded.rs").write_text(embedded_rs)
                await emit("config", "Configuration embedded")

                # Step 3: Compile
                if _is_native_target(request.target):
                    cmd = ["cargo", "build", "--release", "--target", triple]
                    await emit("compile", f"Compiling for {triple} (native)...")
                else:
                    cmd = ["cross", "build", "--release", "--target", triple]
                    await emit("compile", f"Compiling for {triple} (cross)...")

                process = await asyncio.create_subprocess_exec(
                    *cmd,
                    cwd=str(self.sensor_dir),
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )

                # Stream stderr (cargo outputs to stderr)
                async for line in process.stderr:
                    text = line.decode().rstrip()
                    if text:
                        await emit("compile", text)

                await process.wait()

                if process.returncode != 0:
                    stdout = await process.stdout.read()
                    if stdout:
                        await emit("error", stdout.decode())
                    await emit("error", f"Build failed with exit code {process.returncode}")
                    return None

                # Step 4: Locate binary and store for download
                binary_path = (
                    self.sensor_dir / "target" / triple / "release" / binary_name
                )
                if not binary_path.exists():
                    await emit("error", f"Binary not found at {binary_path}")
                    return None

                download_id = uuid.uuid4().hex[:12]
                download_dir = Path(tempfile.gettempdir()) / "leetha-builds"
                download_dir.mkdir(parents=True, exist_ok=True)
                dest = download_dir / f"{download_id}_{binary_name}"
                shutil.copy2(binary_path, dest)
                import os, stat
                dest.chmod(dest.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

                _build_artifacts[download_id] = {
                    "path": str(dest),
                    "filename": binary_name,
                    "created": time.time(),
                    "sensor_name": request.name,
                    "target": request.target,
                }

                # Record successful build in history
                if self.history:
                    self.history.record(request, success=True, download_id=download_id)

                await emit("done", json.dumps({
                    "message": "Build complete",
                    "download_id": download_id,
                    "filename": binary_name,
                }))
                return download_id

            except Exception as e:
                # Record failed build in history
                if self.history:
                    self.history.record(request, success=False)
                await emit("error", f"Build failed: {e}")
                return None
            finally:
                # Restore default embedded.rs (with empty byte literals, not include_bytes!)
                default_rs = '''\
// Auto-generated by leetha build server — do not edit manually.
// Default values used for development and testing.

pub const SENSOR_NAME: &str = "dev-sensor";
pub const SERVER_ADDR: &str = "127.0.0.1:8443";
pub const BUFFER_SIZE_MB: usize = 100;

// Empty certs for development — replaced with include_bytes! during production builds.
pub const CA_PEM: &[u8] = b"";
pub const CERT_PEM: &[u8] = b"";
pub const KEY_PEM: &[u8] = b"";
'''
                (self.sensor_dir / "src" / "embedded.rs").write_text(default_rs)
